In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data=pd.read_csv('zomato_raw_data.csv')
df=raw_data.copy()

In [3]:
df.sample(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
12893,https://www.zomato.com/bangalore/hotel-fanoos-...,"17, Hosur Road, Near Johnson Market, Richmond ...",Hotel Fanoos,Yes,No,4.0/5,787,+91 8892322814\r\n+91 9113292702,Richmond Road,Quick Bites,"Rolls, Shawarma, Beef Roll, Chicken Shawarama,...","Arabian, Biryani, Rolls, Kebab",400,"[('Rated 4.0', 'RATED\n Fanoos- since the 195...",[],Dine-out,Church Street
18905,https://www.zomato.com/bangalore/california-bu...,"23, Ground Floor Sri Avenue 3rd B Cross, 60 Fe...",California Burrito,No,No,4.2/5,253,080 49597749\r\n080 39515101,Indiranagar,Quick Bites,"Rice Bowl, California Burrito, Nachos, Salad, ...","Mexican, Fast Food",400,"[('Rated 4.0', ""RATED\n Ordered a rice bowl a...",[],Dine-out,Indiranagar
50876,https://www.zomato.com/bangalore/the-differenc...,"101/102, 1st Floor, The Arcade, Brigade Metrop...",The Difference,Yes,No,2.7 /5,18,+91 7411252298,Whitefield,Casual Dining,NaN,"North Indian, Chinese, Arabian",600,"[('Rated 3.0', 'RATED\n Had been to this plac...",[],Delivery,Whitefield
13314,https://www.zomato.com/bangalore/watsons-ulsoo...,"Skywalk, 4th Floor, Near Body Craft, Assaye Ro...",Watson's,No,Yes,4.2/5,1428,+91 7760988922\r\n+91 7760988933,Ulsoor,Pub,"Beer, Mocktails, Cocktails, Margherita Pizza, ...","Finger Food, Salad, Chinese, Continental","1,300","[('Rated 5.0', 'RATED\n Service, ambience, fo...",[],Pubs and bars,Church Street
43607,https://www.zomato.com/bangalore/container-cof...,"31, Ground Floor, Ulsoor Road, Near HDFC Bank,...",Container Coffee,Yes,No,3.5 /5,12,+91 9980937325,Ulsoor,Quick Bites,NaN,South Indian,200,"[('Rated 4.0', 'RATED\n This restaurant is in...",[],Dine-out,MG Road

# Remove unwanted columns

In [4]:
columns_to_drop=['url','address','phone','dish_liked','menu_item','location','reviews_list','menu_item']
df.drop(columns=columns_to_drop,inplace=True)

In [5]:
df.sample(5)

,name,online_order,book_table,rate,votes,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
43653,Kerala Home Food,No,No,NaN,0,Quick Bites,Kerala,300,Dine-out,MG Road
38862,Mehendi,No,No,NaN,0,Casual Dining,"North Indian, Chinese",700,Dine-out,Lavelle Road
17137,Om Sai Baba Mess,Yes,No,3.1/5,11,Mess,South Indian,250,Dine-out,HSR
32897,Sri Ganesh Fruit Juice Centre,Yes,No,3.2 /5,4,Beverage Shop,"Juices, Beverages",100,Delivery,Koramangala 6th Block
19536,30 Square,Yes,No,4.2/5,556,Quick Bites,"Tibetan, Nepalese, Momos",400,Delivery,Jayanagar

# Renaming the columns

In [6]:
df.rename(columns={'name':"Name",'rate':'Rating','votes':'Customer_rated',
                   'approx_cost(for two people)':'Cost_for_two','listed_in(type)':'Service_Category','listed_in(city)':'City'},inplace=True)

In [7]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
16178,Amul Ice Cream,Yes,No,NEW,0,Dessert Parlor,"Desserts, Ice Cream",100,Delivery,HSR
6960,Shan-e-Punjabi Express,Yes,No,3.1/5,71,Quick Bites,North Indian,400,Delivery,Brookefield
26430,Naina Nand Food Express,Yes,No,3.4 /5,9,Quick Bites,"North Indian, Chinese",300,Dine-out,Kammanahalli
9756,Al Habibi Restaurant,Yes,No,3.5/5,17,Quick Bites,"North Indian, Chinese",300,Delivery,BTM
8023,Chacha Ka Dhaba,No,No,NEW,0,Quick Bites,"North Indian, Chinese",400,Dine-out,Brookefield

# Remove Duplicates

In [8]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [9]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
32932,Tawa Sagara,No,No,3.8 /5,122,Casual Dining,"Mangalorean, Seafood",NaN,Delivery,Koramangala 6th Block
47625,EatWater,No,No,4.2 /5,121,"Casual Dining, Bar",North Eastern,NaN,Delivery,Residency Road
24732,My China,No,No,3.0/5,14,Casual Dining,"Chinese, Asian, Malaysian",600,Dine-out,Kalyan Nagar
11291,Sri Vinayaka Andhra Mess,No,No,3.3/5,4,Mess,Andhra,300,Dine-out,BTM
21855,Kannur Food Point,Yes,No,3.7/5,215,Quick Bites,"Kerala, North Indian",200,Delivery,JP Nagar

# Split Rating Column

In [10]:
df['Rating_out_of_5']=df['Rating'].str.extract(r'(\d+.\d+|\d+)',expand=True)
df['Rating_out_of_5']=pd.to_numeric(df['Rating_out_of_5'],errors='coerce')

In [11]:
df.drop(columns=['Rating'],inplace=True)

In [12]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
38215,InBento,No,No,0,Delivery,Japanese,900,Delivery,Lavelle Road,NaN
6746,Flechazo,No,Yes,2745,Casual Dining,"Asian, Mediterranean, North Indian, BBQ","1,400",Buffet,Brookefield,4.9
50854,Punjabi Charchay,No,No,31,Quick Bites,"North Indian, Chinese",400,Delivery,Whitefield,3.6
43172,Thanco's Natural Ice Cream,No,No,0,Dessert Parlor,"Ice Cream, Desserts",450,Desserts,MG Road,NaN
45567,The Ganache Factory,Yes,No,42,"Dessert Parlor, Bakery","Desserts, Bakery",400,Desserts,Old Airport Road,4.1

# Clean rest_type column

In [13]:
df['rest_type']=df['rest_type'].str.replace('Cafee','Cafe')

In [14]:
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Delivery', na=False), 'rest_type'] = 'Quick Bites'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Dine-out', na=False), 'rest_type'] = 'Casual Dining'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Cafes', na=False), 'rest_type'] = 'Cafe'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Desserts', na=False), 'rest_type'] = 'Dessert Parlor'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Drinks', na=False), 'rest_type'] = 'Pub,Bar'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Buffet', na=False), 'rest_type'] = 'Buffet'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Pubs and bars', na=False), 'rest_type'] = 'Pub,Bar'

In [15]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
20716,Victoria Terminus,No,No,0,Quick Bites,"Fast Food, Maharashtrian",250,Delivery,Jayanagar,NaN
37890,Caferia,Yes,No,5,Quick Bites,"Fast Food, Street Food",200,Delivery,Lavelle Road,3.3
38961,KKR FOODIES,Yes,Yes,60,Quick Bites,"Fast Food, North Indian",400,Dine-out,Lavelle Road,3.2
5583,Mummy Dhaba,Yes,No,46,Quick Bites,North Indian,300,Delivery,Brigade Road,3.2
38617,Nagarjuna,No,No,1789,Casual Dining,"Andhra, Biryani",800,Dine-out,Lavelle Road,4.3

# Fill missing values for Cost_for_two column

In [16]:
df['Cost_for_two']=df['Cost_for_two'].str.replace(',','')
df['Cost_for_two']=pd.to_numeric(df['Cost_for_two'],errors='coerce')

In [ ]:
df['Cost_for_two'] = df.groupby(['City', 'rest_type'])['Cost_for_two'].transform(lambda x: x.fillna(x.median()))
df['Cost_for_two'] = df.groupby(['City', 'Service_Category'])['Cost_for_two'].transform(lambda x: x.fillna(x.median()))

# fill cuisines column

In [18]:
df['cuisines'] = df['cuisines'].fillna(df.groupby(['City', 'rest_type'])['cuisines'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan))

In [19]:
df['cuisines'] = df['cuisines'].fillna(df.groupby(['City', 'Service_Category'])['cuisines'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan))

In [20]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
36847,Grand Gowdru Hotel,Yes,No,31,Casual Dining,"South Indian, North Indian, Chinese",700.0,Dine-out,Koramangala 7th Block,3.4
2414,Swad Punjab Da,Yes,No,41,Quick Bites,North Indian,150.0,Dine-out,Bannerghatta Road,3.7
19729,Tapri By The Corner,Yes,No,205,Quick Bites,Fast Food,250.0,Delivery,Jayanagar,4.1
48444,Juice Junction,Yes,No,101,Quick Bites,"Juices, Fast Food",150.0,Dine-out,Residency Road,4.0
8689,Cupcake Bliss,Yes,No,4,Delivery,Bakery,250.0,Delivery,BTM,3.4

# Fill rating column

In [ ]:
df['Rating_out_of_5'] = df.groupby(['City', 'cuisines','rest_type'])['Rating_out_of_5'].transform(lambda x: x.fillna(x.median()))

In [22]:
df['Rating_out_of_5'] = df.groupby(['City'])['Rating_out_of_5'].transform(lambda x: x.fillna(x.median()))

# Final Touch and Rearrangement

In [23]:
order=['Name','City','rest_type','cuisines','Cost_for_two','Rating_out_of_5','Customer_rated','Service_Category','online_order','book_table']
df=df[order]

In [24]:
df.rename(columns={'Name':'Restaurant_Name','rest_type':'Restaurant_Type','cuisines':'Cuisines','Cost_for_two':'Cost_for_two','Rating_out_of_5':'Rating_out_of_5','Customer_rated':'Customer_rated','Service_Category':'Service_Category','online_order':'Online_Order','book_table':'Book_Table'},inplace=True)

In [25]:
df.sample(5)

,Restaurant_Name,City,Restaurant_Type,Cuisines,Cost_for_two,Rating_out_of_5,Customer_rated,Service_Category,Online_Order,Book_Table
16102,World Of Kebabs,HSR,Casual Dining,"Mughlai, Awadhi, Kebab",600.0,3.4,5,Delivery,No,No
19597,Cakewala,Jayanagar,Bakery,"Bakery, Desserts",500.0,4.1,232,Delivery,Yes,No
41273,Jaffa's Biryani,Marathahalli,Casual Dining,"Biryani, North Indian, Chinese",650.0,3.8,434,Delivery,Yes,No
7470,Risalo Pizzeria,Brookefield,Quick Bites,"Pizza, Italian, Desserts",900.0,4.0,121,Delivery,Yes,No
22571,Rolls On Wheels,JP Nagar,Quick Bites,"Fast Food, Rolls, Momos",300.0,3.1,138,Delivery,No,No