In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data=pd.read_csv('zomato_raw_data.csv')
df=raw_data.copy()

In [3]:
df.sample(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
24860,https://www.zomato.com/bangalore/yuan-restaura...,"2&3, Renu Arcade, 1st Stage, 2nd Block, 80 Fee...",Yuan Restaurant,Yes,No,3.8/5,202,+91 9901047070\r\n00 08040974045,HBR Layout,Casual Dining,"Momos, Spring Roll, Manchow Soup, Dragon Noodles","Chinese, Momos",600,"[('Rated 4.0', ""RATED\n It's a small outlet t...",[],Dine-out,Kalyan Nagar
51498,https://www.zomato.com/bangalore/mothi-family-...,"454, Whitefield Main Road, Opposite South Indi...",Mothi Family Restaurant,No,No,NaN,0,+91 7795386903,Whitefield,Quick Bites,NaN,"South Indian, North Indian",350,"[('Rated 4.0', 'RATED\n food was great I had ...",[],Dine-out,Whitefield
17110,https://www.zomato.com/bangalore/thalassery-me...,"31, 4th Cross Road, Mangammanapalya, HSR, Bang...",Thalassery Mess,No,No,3.3/5,7,+91 7829745323\r\n+91 8892743136,HSR,Mess,NaN,Kerala,300,"[('Rated 3.5', 'RATED\n Visited them on Sunda...",[],Dine-out,HSR
16500,https://www.zomato.com/bangalore/swad-e-punjab...,"458, Ground Floor, 2nd Main, Outer Ring Road, ...",Swad 'E' Punjab,Yes,No,3.6/5,49,+91 9986006784\r\n080 25533115,HSR,Casual Dining,NaN,"North Indian, Chinese, Mughlai",500,"[('Rated 3.0', 'RATED\n One of the best place...",[],Delivery,HSR
34234,https://www.zomato.com/bangalore/laziz-pizza-k...,"Shop 213, Grace Point, Opposite Bosch Back Gat...",Laziz Pizza,Yes,No,3.8 /5,47,080 49652743,Koramangala 7th Block,Quick Bites,"Pizza, Peri Peri Fries, Veg Paprika","Fast Food, Burger, Pizza",400,"[('Rated 2.0', ""RATED\n Zomato was running an...",[],Dine-out,Koramangala 6th Block

# Remove unwanted columns

In [4]:
columns_to_drop=['url','address','phone','dish_liked','menu_item','location','reviews_list','menu_item']
df.drop(columns=columns_to_drop,inplace=True)

In [5]:
df.sample(5)

,name,online_order,book_table,rate,votes,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
40556,Risalo Restaurant,No,No,NaN,0,NaN,NaN,NaN,Cafes,Marathahalli
16409,Mynutrikitchen,Yes,No,3.6/5,59,Delivery,"North Indian, Healthy Food",300,Delivery,HSR
42382,Soda Bottle Opener Wala,Yes,Yes,4.5 /5,3709,"Casual Dining, Irani Cafee","Parsi, North Indian","1,300",Delivery,MG Road
9865,Midnight Hunger Solutions 24/7,No,No,3.2/5,11,Delivery,"North Indian, Mughlai, Chinese",500,Delivery,BTM
29617,McDonald's,Yes,No,3.8 /5,295,Quick Bites,"Fast Food, Burger",500,Delivery,Koramangala 5th Block

# Renaming the columns

In [6]:
df.rename(columns={'name':"Name",'rate':'Rating','votes':'Customer_rated',
                   'approx_cost(for two people)':'Cost_for_two','listed_in(type)':'Service_Category','listed_in(city)':'City'},inplace=True)

In [7]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
2847,Mr. Parathewala,Yes,No,NaN,0,"Takeaway, Delivery",North Indian,300,Delivery,Basavanagudi
38769,Desi Inn,Yes,No,3.5 /5,13,Quick Bites,North Indian,300,Dine-out,Lavelle Road
49536,Delhi Food Factory,Yes,No,NaN,0,Delivery,North Indian,500,Delivery,Sarjapur Road
6243,Polo Club - The Oberoi,No,No,4.1/5,117,Fine Dining,"American, North Indian, European, Tex-Mex","3,000",Dine-out,Brigade Road
19409,The Maori - Aurick Boutique Hotel,No,No,3.5/5,44,Casual Dining,"Chinese, North Indian","1,000",Buffet,Jayanagar

# Remove Duplicates

In [8]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [9]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
19925,Domino's Pizza,Yes,No,3.7/5,386,Quick Bites,"Pizza, Fast Food",400,Delivery,Jayanagar
17631,CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Felix,Yes,Yes,4.4/5,688,"Casual Dining, Cafe","American, Cafe, Continental","1,700",Cafes,Indiranagar
13571,The Mirchi,Yes,No,3.3/5,22,"Takeaway, Delivery","Chinese, North Indian, Bengali",400,Delivery,Electronic City
4872,Baba Da Dhaba,No,Yes,3.6/5,32,Casual Dining,North Indian,650,Dine-out,Bellandur
19586,Onesta,Yes,Yes,4.6/5,2604,"Casual Dining, Cafe","Pizza, Cafe, Italian",600,Delivery,Jayanagar

# Split Rating Column

In [10]:
df['Rating_out_of_5']=df['Rating'].str.extract(r'(\d+.\d+|\d+)',expand=True)
df['Rating_out_of_5']=pd.to_numeric(df['Rating_out_of_5'],errors='coerce')

In [11]:
df.drop(columns=['Rating'],inplace=True)

In [12]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
6076,Portland Steakhouse & Cafe,Yes,Yes,2040,Casual Dining,"Steak, Italian, Continental, American, Burger,...","1,500",Dine-out,Brigade Road,4.3
34641,Barkat,No,No,6,Quick Bites,Kerala,250,Dine-out,Koramangala 6th Block,3.4
44926,Smally's Resto Cafe,Yes,No,424,Cafe,"Cafe, Italian, Burger, American, Steak",650,Delivery,Old Airport Road,4.1
4460,Kakatiya's,Yes,No,6,Quick Bites,"South Indian, Biryani",250,Delivery,Bellandur,3.1
29904,Cream Chemistry,Yes,No,231,Dessert Parlor,"Ice Cream, Desserts",500,Delivery,Koramangala 5th Block,3.9

# Clean rest_type column

In [13]:
df['rest_type']=df['rest_type'].str.replace('Cafee','Cafe')

In [14]:
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Delivery', na=False), 'rest_type'] = 'Quick Bites'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Dine-out', na=False), 'rest_type'] = 'Casual Dining'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Cafes', na=False), 'rest_type'] = 'Cafe'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Desserts', na=False), 'rest_type'] = 'Dessert Parlor'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Drinks', na=False), 'rest_type'] = 'Pub,Bar'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Buffet', na=False), 'rest_type'] = 'Buffet'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Pubs and bars', na=False), 'rest_type'] = 'Pub,Bar'

In [15]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
38018,The Belgian Waffle Co.,Yes,No,75,Dessert Parlor,"Desserts, Beverages",350,Delivery,Lavelle Road,3.7
15229,Rolls On Wheels,No,No,61,Quick Bites,"Fast Food, Rolls, Momos",200,Delivery,Frazer Town,3.7
50759,Umami & Beyond,No,No,0,Delivery,"American, Thai, Healthy Food",500,Delivery,Whitefield,NaN
9868,Owly,No,No,27,Delivery,"Fast Food, North Indian",350,Delivery,BTM,3.7
20062,3 Spice,Yes,No,157,Casual Dining,"North Indian, Chinese",450,Delivery,Jayanagar,3.9

# Fill missing values for Cost_for_two column

In [16]:
df['Cost_for_two']=df['Cost_for_two'].str.replace(',','')
df['Cost_for_two']=pd.to_numeric(df['Cost_for_two'],errors='coerce')

In [17]:
df['Cost_for_two'] = df.groupby(['City', 'rest_type'])['Cost_for_two'].transform(lambda x: x.fillna(x.median()))
df['Cost_for_two'] = df.groupby(['City', 'Service_Category'])['Cost_for_two'].transform(lambda x: x.fillna(x.median()))

d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

# fill cuisines column

In [18]:
df['cuisines'] = df['cuisines'].fillna(df.groupby(['City', 'rest_type'])['cuisines'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan))

In [19]:
df['cuisines'] = df['cuisines'].fillna(df.groupby(['City', 'Service_Category'])['cuisines'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan))

In [20]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
6325,The Bao Belly,No,No,9,Cafe,Cafe,400.0,Dine-out,Brigade Road,3.3
36396,BelgYum,Yes,No,69,Dessert Parlor,Desserts,400.0,Desserts,Koramangala 7th Block,4.0
42856,Truffles,No,No,3595,Cafe,"Cafe, American, Burger, Steak",900.0,Delivery,MG Road,4.5
46698,Apsara Ice Cream,Yes,No,25,Dessert Parlor,"Ice Cream, Desserts",200.0,Desserts,Rajajinagar,4.0
14420,MKA Ambur Hot Dum Biriyani,No,No,0,Quick Bites,Biryani,200.0,Dine-out,Electronic City,NaN

# Fill rating column

In [ ]:
df['Rating_out_of_5'] = df.groupby(['City', 'cuisines','rest_type'])['Rating_out_of_5'].transform(lambda x: x.fillna(x.median()))

In [22]:
df['Rating_out_of_5'] = df.groupby(['City'])['Rating_out_of_5'].transform(lambda x: x.fillna(x.median()))