In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data=pd.read_csv('zomato_raw_data.csv')
df=raw_data.copy()

In [3]:
df.sample(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
20894,https://www.zomato.com/bangalore/durga-bikaner...,"38, Near ICICI Bank Signal, 4th F Cross, 8th M...",Durga Bikaner Sweets,No,No,3.7/5,15,+91 9916574352,Jayanagar,Quick Bites,NaN,"Street Food, Mithai",100,"[('Rated 4.0', ""RATED\n Another famous spot i...",[],Desserts,Jayanagar
35141,https://www.zomato.com/bangalore/pin-me-down-b...,"29, Tavakere Main Road, Behind Forum Mall, Kor...",Pin Me Down,Yes,Yes,4.5 /5,819,+91 8861568945\n+91 8178831745,BTM,Casual Dining,"Paneer Tikka, Pasta, Chilli Chicken, Pizza, Mo...","Continental, Mexican, Chinese, North Indian",800,"[('Rated 3.0', ""RATED\n The food and ambience...",[],Delivery,Koramangala 7th Block
13439,https://www.zomato.com/bangalore/fish-chain-el...,"Kitchens@, 1st Floor Skywards Sun Park, Neelad...",Fish Chain,Yes,No,NEW,0,080 43334333,Electronic City,"Takeaway, Delivery",NaN,"Seafood, BBQ, Biryani",250,"[('Rated 5.0', 'RATED\n I ordered from this p...",[],Delivery,Electronic City
4939,https://www.zomato.com/bangalore/sharaab-facto...,"3, 6th Floor, Bangalore Central Mall, Bellandu...",Sharaab Factory,Yes,Yes,3.9/5,392,+91 9901755559\r\n+91 8951444448,Bellandur,Bar,"Chicken Curry, Chicken Tikka, Cocktails, Long ...","Biryani, North Indian","1,500","[('Rated 3.0', 'RATED\n Yet another impromptu...","['Hing Wali Dal Shorba', 'Bhune Tamatar aur Dh...",Drinks & nightlife,Bellandur
38402,https://www.zomato.com/bangalore/hyper-scoop-s...,"76/1, Mission Road, Subbayya Circle, Shanti Na...",Hyper Scoop,Yes,No,NaN,0,+91 9902755155\n+91 9845656928,Shanti Nagar,Dessert Parlor,NaN,"Desserts, Ice Cream",300,[],[],Delivery,Lavelle Road

# Remove unwanted columns

In [4]:
columns_to_drop=['url','address','phone','dish_liked','menu_item','location','reviews_list','menu_item']
df.drop(columns=columns_to_drop,inplace=True)

In [5]:
df.sample(5)

,name,online_order,book_table,rate,votes,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
2785,Kettle & Kegs,Yes,No,3.2/5,6,Delivery,"Tea, Beverages",200,Delivery,Basavanagudi
35763,Harry's Bar + Cafe,Yes,Yes,4.2 /5,1370,"Casual Dining, Bar","Asian, American, Mexican","1,400",Delivery,Koramangala 7th Block
15293,Sri Rama,No,No,3.2/5,4,Quick Bites,South Indian,200,Delivery,Frazer Town
15049,Mamma Mexicana,Yes,Yes,2.2/5,406,Casual Dining,Mexican,"1,000",Delivery,Frazer Town
2132,New Royal Treat,Yes,No,2.8/5,102,Quick Bites,"North Indian, Chinese",350,Dine-out,Bannerghatta Road

# Renaming the columns

In [6]:
df.rename(columns={'name':"Name",'rate':'Rating','votes':'Customer_rated',
                   'approx_cost(for two people)':'Cost_for_two','listed_in(type)':'Service_Category','listed_in(city)':'City'},inplace=True)

In [7]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
49058,Abbabi Chicken,No,No,3.7 /5,134,Quick Bites,Fast Food,200,Delivery,Sarjapur Road
28821,Hotel Thazooq,No,No,3.3 /5,6,Quick Bites,"North Indian, Chinese, Biryani",350,Dine-out,Koramangala 4th Block
27706,Star Bowl,Yes,No,NEW,0,"Takeaway, Delivery","North Indian, Chinese, Rolls",650,Delivery,Koramangala 4th Block
46860,Dhanya Nati Style Restaurant,No,No,3.1 /5,37,Quick Bites,South Indian,300,Dine-out,Rajajinagar
43967,Engine,No,No,3.3 /5,16,"Casual Dining, Bar","Biryani, South Indian, North Indian, Chinese, ...",950,Pubs and bars,MG Road

# Remove Duplicates

In [ ]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

np.int64(124)

In [10]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
51306,The Coffee Bean & Tea Leaf,Yes,No,3.0 /5,38,Cafe,"Cafe, Coffee",700,Dine-out,Whitefield
36817,7 Plates,Yes,No,3.7 /5,259,Casual Dining,"Mughlai, Fast Food",750,Dine-out,Koramangala 7th Block
38472,The Waffle Press,Yes,No,4.3 /5,120,Dessert Parlor,"Desserts, Ice Cream",400,Desserts,Lavelle Road
43250,Nagarjuna,No,No,4.3 /5,1792,Casual Dining,"Andhra, Biryani",800,Dine-out,MG Road
28350,Vasudev Adiga's,No,No,2.8 /5,289,Casual Dining,"South Indian, North Indian, Chinese, Street Food",250,Dine-out,Koramangala 4th Block

# Split Rating Column

In [12]:
df['Rating_out_of_5']=df['Rating'].str.extract(r'(\d+.\d+|\d+)',expand=True)
df['Rating_out_of_5']=pd.to_numeric(df['Rating_out_of_5'],errors='coerce')

In [15]:
df.drop(columns=['Rating'],inplace=True)

In [16]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
20714,Wellness Cafe,No,No,0,Cafe,"Cafe, Healthy Food",400,Delivery,Jayanagar,NaN
23772,Armaani Caffe,Yes,No,12,Quick Bites,Fast Food,250,Dine-out,JP Nagar,3.5
33837,Cashmere Nites,Yes,No,74,Casual Dining,Kashmiri,600,Dine-out,Koramangala 6th Block,3.5
1589,Foodiction,No,No,54,Quick Bites,"North Indian, Fast Food, Chinese, Burger",500,Delivery,Bannerghatta Road,2.9
6119,The Open Box,Yes,Yes,2270,"Casual Dining, Bar","European, North Indian, Mediterranean, Asian, ...","1,400",Dine-out,Brigade Road,4.2