In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data=pd.read_csv('zomato_raw_data.csv')
df=raw_data.copy()

In [3]:
df.sample(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
17694,https://www.zomato.com/bangalore/chakh-le-food...,"513, First Floor, 10th Main Road, Jeevan Bhima...",Chakh Le Foods,Yes,Yes,3.4/5,257,080 41255090\r\n+91 9035043643,Jeevan Bhima Nagar,Casual Dining,"Fish, Aloo Posto","North Indian, Mughlai, Bengali, Chinese",500,"[('Rated 2.0', ""RATED\n Ordered Chicken thali...",[],Delivery,Indiranagar
18865,https://www.zomato.com/bangalore/dominos-pizza...,"308, 2nd Stage, 100 Feet Road, Indiranagar, Ba...",Domino's Pizza,Yes,No,3.0/5,464,080 25217444\r\n18602100000,Indiranagar,Quick Bites,"Pane Pizza, Garlic Bread, Pepperoni Pizza, Cho...","Pizza, Fast Food",800,"[('Rated 4.0', 'RATED\n I went to dominos in ...","['Margherita', 'Farmhouse', 'Mexican Green Wav...",Dine-out,Indiranagar
20120,https://www.zomato.com/bangalore/tandoor-merch...,"18, 4th Cross, 4th Link Road, Maruthi Nagar, M...",Tandoor Merchant,Yes,No,3.4/5,22,+91 7259015811,BTM,"Takeaway, Delivery",NaN,"North Indian, Chinese, Fast Food",500,"[('Rated 2.0', ""RATED\n The food is not good ...","['Peanut Masala', 'French Fry', 'Chicken Pakod...",Delivery,Jayanagar
11558,https://www.zomato.com/bangalore/the-market-th...,"The Ritz-Carlton, 99, Residency Road, Bangalore",The Market - The Ritz-Carlton,No,Yes,4.3/5,614,080 49148341,Residency Road,Fine Dining,"Pizza, Waffles, Pasta, Sushi, Salads, Fish, Co...","North Indian, European, Thai","3,400","[('Rated 3.0', 'RATED\n Went there for buffet...",[],Buffet,Church Street
11277,https://www.zomato.com/bangalore/nandhanus-ras...,"#2035, 26th Main, South F Cross, Opposite Ragi...",Nandhanus Rasoi,Yes,No,3.4/5,9,+91 9632490428,Jayanagar,Quick Bites,NaN,"Chinese, Rolls, North Indian",200,"[('Rated 1.0', ""RATED\n Horrible tawa palau r...",[],Dine-out,BTM

# Remove unwanted columns

In [4]:
columns_to_drop=['url','address','phone','dish_liked','menu_item','location','reviews_list','menu_item']
df.drop(columns=columns_to_drop,inplace=True)

In [5]:
df.sample(5)

,name,online_order,book_table,rate,votes,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
7935,Chaat Street,Yes,No,4.1/5,219,Kiosk,"Street Food, North Indian",250,Dine-out,Brookefield
50234,KBC - Kebab Biryani Curry,Yes,No,3.4 /5,38,Quick Bites,"North Indian, Chinese, Kebab, Biryani",400,Delivery,Whitefield
26247,Taste Of The Nation,No,No,3.0 /5,110,NaN,North Indian,650,Dine-out,Kammanahalli
1126,Keventers,Yes,No,3.8/5,29,"Beverage Shop, Dessert Parlor","Desserts, Beverages, Ice Cream",400,Delivery,Bannerghatta Road
38560,Brownie Heaven,Yes,No,4.2 /5,34,Dessert Parlor,"Desserts, Fast Food",300,Desserts,Lavelle Road

# Renaming the columns

In [6]:
df.rename(columns={'name':"Name",'rate':'Rating','votes':'Customer_rated',
                   'approx_cost(for two people)':'Cost_for_two','listed_in(type)':'Service_Category','listed_in(city)':'City'},inplace=True)

In [7]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
381,Utsav Restaurant,Yes,No,3.8/5,61,Quick Bites,"North Indian, Chinese",300,Delivery,Banashankari
23925,Imperio Restaurant,Yes,Yes,4.5/5,1228,Casual Dining,"North Indian, Mughlai, Biryani, South Indian, ...",800,Delivery,Kalyan Nagar
11399,SS Food Point,No,No,NaN,0,Quick Bites,"South Indian, Biryani",250,Dine-out,BTM
25281,Pizza Hut,Yes,No,2.7/5,434,Casual Dining,"Pizza, Fast Food",750,Delivery,Kammanahalli
50444,Andhra Taste,Yes,No,NaN,0,Delivery,Andhra,400,Delivery,Whitefield

# Remove Duplicates

In [8]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [9]:
df.sample(5)

,Name,online_order,book_table,Rating,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City
37911,Wangs Kitchen,Yes,No,2.5 /5,22,Casual Dining,Chinese,"1,000",Delivery,Lavelle Road
26120,Sri Durga Nellore Mess,Yes,No,3.4 /5,356,Mess,"Andhra, South Indian, Biryani",350,Dine-out,Kammanahalli
24953,Food Box Restaurant,No,No,NaN,0,Quick Bites,Fast Food,400,Dine-out,Kalyan Nagar
41137,Ginger & Garlic,Yes,No,3.6 /5,92,Quick Bites,"South Indian, North Indian, Chinese",350,Delivery,Marathahalli
43849,The Biere Club,Yes,Yes,4.3 /5,3496,"Pub, Microbrewery","Continental, BBQ, Finger Food","1,700",Drinks & nightlife,MG Road

# Split Rating Column

In [10]:
df['Rating_out_of_5']=df['Rating'].str.extract(r'(\d+.\d+|\d+)',expand=True)
df['Rating_out_of_5']=pd.to_numeric(df['Rating_out_of_5'],errors='coerce')

In [11]:
df.drop(columns=['Rating'],inplace=True)

In [12]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
42044,Jade,Yes,Yes,692,Casual Dining,"Chinese, Seafood, Momos",750,Dine-out,Marathahalli,3.7
13460,KFC,Yes,No,682,Quick Bites,"Burger, Fast Food",450,Delivery,Electronic City,3.9
41101,New Royal Treat,Yes,No,0,Quick Bites,"North Indian, Chinese",350,Delivery,Marathahalli,NaN
50267,Khan Saheb Grills and Rolls,Yes,No,305,Quick Bites,"Fast Food, Rolls",400,Delivery,Whitefield,3.8
7558,Tasty Box,Yes,No,0,Delivery,"Arabian, Mughlai, Chinese, Biryani",300,Delivery,Brookefield,NaN

# Clean rest_type column

In [13]:
df['rest_type']=df['rest_type'].str.replace('Cafee','Cafe')

In [14]:
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Delivery', na=False), 'rest_type'] = 'Quick Bites'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Dine-out', na=False), 'rest_type'] = 'Casual Dining'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Cafes', na=False), 'rest_type'] = 'Cafe'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Desserts', na=False), 'rest_type'] = 'Dessert Parlor'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Drinks', na=False), 'rest_type'] = 'Pub,Bar'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Buffet', na=False), 'rest_type'] = 'Buffet'
df.loc[df['rest_type'].isna() & df['Service_Category'].str.contains('Pubs and bars', na=False), 'rest_type'] = 'Pub,Bar'

In [15]:
df.sample(5)

,Name,online_order,book_table,Customer_rated,rest_type,cuisines,Cost_for_two,Service_Category,City,Rating_out_of_5
47988,Bengaluru Baking Company - JW Marriott Bengaluru,No,No,526,"Bakery, Cafe","Salad, Bakery, Cafe, Sandwich, Italian, Burger","1,400",Desserts,Residency Road,4.3
49802,Mane Ruchii,No,No,0,Quick Bites,"South Indian, Chinese, Kebab",400,Dine-out,Sarjapur Road,NaN
18520,Cake Genie,No,No,149,Dessert Parlor,"Desserts, Fast Food",300,Desserts,Indiranagar,3.9
10638,Veruthe Oru Thattukada,Yes,No,27,Quick Bites,"Kerala, South Indian",400,Dine-out,BTM,3.7
25112,New Udupi Park Deluxe,No,No,77,Quick Bites,"South Indian, North Indian, Chinese",400,Dine-out,Kalyan Nagar,3.6

# Fill missing values for Cost_for_two column

In [16]:
df['Cost_for_two']=df['Cost_for_two'].str.replace(',','')
df['Cost_for_two']=pd.to_numeric(df['Cost_for_two'],errors='coerce')

In [17]:
df['Cost_for_two'] = df.groupby(['City', 'rest_type'])['Cost_for_two'].transform(lambda x: x.fillna(x.median()))
df['Cost_for_two'] = df.groupby(['City', 'Service_Category'])['Cost_for_two'].transform(lambda x: x.fillna(x.median()))

d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Shourya_Personal_Files\Python_Directories\Python_Projects\Zoamto_Dataset\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)